create table if not exists book (

    id bigint primary key generated by default as identity not null,
    isbn varchar(255) unique not null,
    name varchar(255) not null,
    genre varchar(255) not null,
    description varchar(255),
    author varchar(255) not null

)