INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-306-40615-7', 'The Catcher in the Rye', 'Fiction', 'A classic novel about teenage angst and alienation.', 'J.D. Salinger');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-060-11208-4', 'To Kill a Mockingbird', 'Fiction', 'A novel about racial injustice in the American South.', 'Harper Lee');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-451-52493-5', '1984', 'Dystopian', 'A dystopian novel about a totalitarian society.', 'George Orwell');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-679-72316-5', 'The Great Gatsby', 'Fiction', 'A novel about the American Dream in the 1920s.', 'F. Scott Fitzgerald');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-060-93546-7', 'The Hobbit', 'Fantasy', 'A fantasy novel about the adventures of Bilbo Baggins.', 'J.R.R. Tolkien');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-399-50148-7', 'Harry Potter and the Philosopher''s Stone', 'Fantasy', 'The first library in the Harry Potter series.', 'J.K. Rowling');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-385-49081-8', 'The Da Vinci Code', 'Thriller', 'A mystery thriller about a secret society.', 'Dan Brown');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-399-15781-0', 'The Hunger Games', 'Dystopian', 'A dystopian novel about a future where children fight to the death.', 'Suzanne Collins');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-316-76948-8', 'The Fault in Our Stars', 'Young Adult', 'A novel about two teenagers with cancer who fall in love.', 'John Green');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-385-47257-9', 'The Girl on the Train', 'Thriller', 'A psychological thriller about a woman who witnesses a crime.', 'Paula Hawkins');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-399-15411-8', 'Gone Girl', 'Thriller', 'A psychological thriller about a missing wife.', 'Gillian Flynn');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-399-17632-4', 'The Night Circus', 'Fantasy', 'A magical novel about a circus that appears without warning.', 'Erin Morgenstern');
INSERT INTO book(isbn, name, genre, description, author)VALUES ('978-0-399-15779-7', 'The Goldfinch', 'Fiction', 'A novel about a boy who survives a terrorist attack.', 'Donna Tartt');
