create table if not exists free_books (

    id bigint primary key generated by default as identity not null,
    book_id bigint not null unique,
    borrowed_at timestamp,
    return_by timestamp

);